### ISSUE TITLE
Events ordering is still problematic

### ISSUE THREAD

**Issue by eezcjkr** [leapdao/leap-node#164]
At the moment all events are pushed into the same priority-queue, ordered by block-number. However this still means that Deposit4 can be ahed of Deposit3 in the queue, which will halt the node. 
Proposed solution: have a separate queue for each independent event-streams.

**Comment by johannbarbie** [comment]
> which will halt the node

will it really?
the `bridgeState` just makes sure that the deposit has been seen at all: https://github.com/leapdao/leap-node/blob/master/src/tx/applyTx/checkDeposit.js#L30
while the state strictly orders the deposits: https://github.com/leapdao/leap-node/blob/master/src/tx/applyTx/checkDeposit.js#L20
i think the only thing that could happen is that the node stops picking up deposits, until deposit4 (rejected first time because of state check) is proposed again, no?
