### ISSUE TITLE
introduce a flag to turn spending condition on / off

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/leap-node#188]
on testnet we want to run spending conditions, on mainnet we don't. we don't want to keep separate forks of the code for different networks, hence a way to define the support for spending conditions when starting the node would be nice.

**Comment by troggy** [comment]
taking this one

**Comment by troggy** [comment]
will add a flag `--noSpendingConditions`. Default is `false`. 

For mainnet we would need to run the nodes with `--noSpendingConditions`

**Comment by troggy** [comment]
this setting is a part of consensus, so I guess it should it be a network-wide setting? Like `eventDelay`

**Comment by troggy** [comment]
added network config option `noSpendingConditions`. Default is `false`. Setting as `true` in `leap-mainnet` config

**Comment by johannbarbie** [comment]
how can we upgrade a network from inactive to active, if this is a config param?

**Comment by troggy** [comment]
good question. I guess it is possible by restarting the nodes one-by-one (using redundant readonly nodes). Not really solid approach, because may lead to consensus errors (one validator is already restarted, the other is not, but spending condition submitted — 💥). Better idea, probably, would be to specify a block height from which to turn spencons from. But this will renders this flag as one time only

**Comment by johannbarbie** [comment]
maybe something like an anti-ice-age, where it would activate unless we extend the period again.
